# Generated by Django 4.2.5 on 2023-10-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0005_alter_placename_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Отчество"
                    ),
                ),
                (
                    "tour_name",
                    models.CharField(max_length=128, verbose_name="Название экскурсии"),
                ),
                ("description", models.TextField(verbose_name="Описание тура")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Стоимость экскурсии",
                    ),
                ),
                (
                    "places",
                    models.ManyToManyField(
                        related_name="tour_guides",
                        to="places.placename",
                        verbose_name="Места",
                    ),
                ),
            ],
            options={
                "verbose_name": "Экскурсовод",
                "verbose_name_plural": "Экскурсоводы",
            },
        ),
    ]
